
'use server';

/**
 * @fileOverview Generates a wellness report from the user's chat history, analyzed from the perspective of an AI psychotherapist.
 * The report provides a summary of insights, potential discussion points for a mental health professional, and motivational advice, along with necessary disclaimers.
 *
 * - generateReport - A function that generates the report from chat history.
 * - GenerateReportInput - The input type for the generateReport function.
 * - GenerateReportOutput - The return type for the generateReport function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateReportInputSchema = z.object({
  chatHistory: z
    .string()
    .describe('The complete chat history of the user with TheraBot.'),
});
export type GenerateReportInput = z.infer<typeof GenerateReportInputSchema>;

const GenerateReportOutputSchema = z.object({
  report: z.string().describe('The generated wellness report containing a summary, potential areas of concern, motivational advice, and disclaimers.'),
});
export type GenerateReportOutput = z.infer<typeof GenerateReportOutputSchema>;

export async function generateReport(input: GenerateReportInput): Promise<GenerateReportOutput> {
  return generateReportFlow(input);
}

const generateReportPrompt = ai.definePrompt({
  name: 'generatePsychotherapistReportPrompt',
  input: {schema: GenerateReportInputSchema},
  output: {schema: GenerateReportOutputSchema},
  prompt: `You are an AI psychotherapist. Your task is to generate a comprehensive wellness report based on the user's provided chat history with TheraBot.

Analyze the chat history thoroughly. The report should include the following sections:
1.  **Summary of Key Themes:** Briefly summarize the main topics and emotional themes discussed.
2.  **Observed Patterns & Insights:** Identify any recurring behavioral patterns, emotional responses, or cognitive themes. What insights can be drawn from these observations?
3.  **Potential Areas for Reflection or Discussion:** Based on the conversation, what specific areas, feelings, or situations might the user benefit from reflecting on further? If there are patterns indicative of common mental wellness concerns (e.g., signs of anxiety, low mood, stress), gently highlight these as potential topics for discussion with a qualified mental health professional. DO NOT provide a definitive diagnosis of any mental illness.
4.  **Strengths and Positive Aspects:** Identify any strengths, coping mechanisms, or positive steps the user has mentioned or demonstrated.
5.  **Motivational Advice & Wellness Suggestions:** Offer general, supportive, and motivational advice that is relevant to the themes discussed. Suggest constructive coping strategies or wellness practices if appropriate.

**Crucial Disclaimer (MUST be included at the end of the report):**
"**Important Disclaimer:** This report is generated by an AI (TheraBot) based on your chat history. It is intended for informational and reflective purposes only and should not be considered a substitute for professional medical advice, diagnosis, or treatment. The insights provided are not medical diagnoses. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition or mental health. Never disregard professional medical advice or delay in seeking it because of something you have read in this report."

Chat History:
{{{chatHistory}}}

Begin the report now.
`,
});

const generateReportFlow = ai.defineFlow(
  {
    name: 'generateReportFlow',
    inputSchema: GenerateReportInputSchema,
    outputSchema: GenerateReportOutputSchema,
  },
  async input => {
    const {output} = await generateReportPrompt(input);
    return output!;
  }
);
